// automatically generated by the FlatBuffers compiler, do not modify

package com.mattygiedt.flatbuffer.marketdata;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MarketDataSnapshot extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static MarketDataSnapshot getRootAsMarketDataSnapshot(ByteBuffer _bb) { return getRootAsMarketDataSnapshot(_bb, new MarketDataSnapshot()); }
  public static MarketDataSnapshot getRootAsMarketDataSnapshot(ByteBuffer _bb, MarketDataSnapshot obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MarketDataSnapshot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long instrumentId() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public boolean mutateInstrumentId(long instrument_id) { int o = __offset(4); if (o != 0) { bb.putInt(o + bb_pos, (int) instrument_id); return true; } else { return false; } }
  public int source() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateSource(int source) { int o = __offset(6); if (o != 0) { bb.put(o + bb_pos, (byte) source); return true; } else { return false; } }
  public com.mattygiedt.flatbuffer.marketdata.EpochNanos createTm() { return createTm(new com.mattygiedt.flatbuffer.marketdata.EpochNanos()); }
  public com.mattygiedt.flatbuffer.marketdata.EpochNanos createTm(com.mattygiedt.flatbuffer.marketdata.EpochNanos obj) { int o = __offset(8); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public com.mattygiedt.flatbuffer.marketdata.Price bidPrice() { return bidPrice(new com.mattygiedt.flatbuffer.marketdata.Price()); }
  public com.mattygiedt.flatbuffer.marketdata.Price bidPrice(com.mattygiedt.flatbuffer.marketdata.Price obj) { int o = __offset(10); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public com.mattygiedt.flatbuffer.marketdata.Price bidYield() { return bidYield(new com.mattygiedt.flatbuffer.marketdata.Price()); }
  public com.mattygiedt.flatbuffer.marketdata.Price bidYield(com.mattygiedt.flatbuffer.marketdata.Price obj) { int o = __offset(12); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public com.mattygiedt.flatbuffer.marketdata.Price bidSpread() { return bidSpread(new com.mattygiedt.flatbuffer.marketdata.Price()); }
  public com.mattygiedt.flatbuffer.marketdata.Price bidSpread(com.mattygiedt.flatbuffer.marketdata.Price obj) { int o = __offset(14); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public com.mattygiedt.flatbuffer.marketdata.Price bidGspread() { return bidGspread(new com.mattygiedt.flatbuffer.marketdata.Price()); }
  public com.mattygiedt.flatbuffer.marketdata.Price bidGspread(com.mattygiedt.flatbuffer.marketdata.Price obj) { int o = __offset(16); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public com.mattygiedt.flatbuffer.marketdata.Price askPrice() { return askPrice(new com.mattygiedt.flatbuffer.marketdata.Price()); }
  public com.mattygiedt.flatbuffer.marketdata.Price askPrice(com.mattygiedt.flatbuffer.marketdata.Price obj) { int o = __offset(18); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public com.mattygiedt.flatbuffer.marketdata.Price askYield() { return askYield(new com.mattygiedt.flatbuffer.marketdata.Price()); }
  public com.mattygiedt.flatbuffer.marketdata.Price askYield(com.mattygiedt.flatbuffer.marketdata.Price obj) { int o = __offset(20); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public com.mattygiedt.flatbuffer.marketdata.Price askSpread() { return askSpread(new com.mattygiedt.flatbuffer.marketdata.Price()); }
  public com.mattygiedt.flatbuffer.marketdata.Price askSpread(com.mattygiedt.flatbuffer.marketdata.Price obj) { int o = __offset(22); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public com.mattygiedt.flatbuffer.marketdata.Price askGspread() { return askGspread(new com.mattygiedt.flatbuffer.marketdata.Price()); }
  public com.mattygiedt.flatbuffer.marketdata.Price askGspread(com.mattygiedt.flatbuffer.marketdata.Price obj) { int o = __offset(24); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public com.mattygiedt.flatbuffer.marketdata.Quantity bidSize() { return bidSize(new com.mattygiedt.flatbuffer.marketdata.Quantity()); }
  public com.mattygiedt.flatbuffer.marketdata.Quantity bidSize(com.mattygiedt.flatbuffer.marketdata.Quantity obj) { int o = __offset(26); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public com.mattygiedt.flatbuffer.marketdata.Quantity askSize() { return askSize(new com.mattygiedt.flatbuffer.marketdata.Quantity()); }
  public com.mattygiedt.flatbuffer.marketdata.Quantity askSize(com.mattygiedt.flatbuffer.marketdata.Quantity obj) { int o = __offset(28); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public com.mattygiedt.flatbuffer.marketdata.Quantity lastTradeSize() { return lastTradeSize(new com.mattygiedt.flatbuffer.marketdata.Quantity()); }
  public com.mattygiedt.flatbuffer.marketdata.Quantity lastTradeSize(com.mattygiedt.flatbuffer.marketdata.Quantity obj) { int o = __offset(30); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public com.mattygiedt.flatbuffer.marketdata.Price lastTradePrice() { return lastTradePrice(new com.mattygiedt.flatbuffer.marketdata.Price()); }
  public com.mattygiedt.flatbuffer.marketdata.Price lastTradePrice(com.mattygiedt.flatbuffer.marketdata.Price obj) { int o = __offset(32); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public com.mattygiedt.flatbuffer.marketdata.EpochNanos lastTradeTm() { return lastTradeTm(new com.mattygiedt.flatbuffer.marketdata.EpochNanos()); }
  public com.mattygiedt.flatbuffer.marketdata.EpochNanos lastTradeTm(com.mattygiedt.flatbuffer.marketdata.EpochNanos obj) { int o = __offset(34); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startMarketDataSnapshot(FlatBufferBuilder builder) { builder.startTable(16); }
  public static void addInstrumentId(FlatBufferBuilder builder, long instrumentId) { builder.addInt(0, (int) instrumentId, (int) 0L); }
  public static void addSource(FlatBufferBuilder builder, int source) { builder.addByte(1, (byte) source, (byte) 0); }
  public static void addCreateTm(FlatBufferBuilder builder, int createTmOffset) { builder.addStruct(2, createTmOffset, 0); }
  public static void addBidPrice(FlatBufferBuilder builder, int bidPriceOffset) { builder.addStruct(3, bidPriceOffset, 0); }
  public static void addBidYield(FlatBufferBuilder builder, int bidYieldOffset) { builder.addStruct(4, bidYieldOffset, 0); }
  public static void addBidSpread(FlatBufferBuilder builder, int bidSpreadOffset) { builder.addStruct(5, bidSpreadOffset, 0); }
  public static void addBidGspread(FlatBufferBuilder builder, int bidGspreadOffset) { builder.addStruct(6, bidGspreadOffset, 0); }
  public static void addAskPrice(FlatBufferBuilder builder, int askPriceOffset) { builder.addStruct(7, askPriceOffset, 0); }
  public static void addAskYield(FlatBufferBuilder builder, int askYieldOffset) { builder.addStruct(8, askYieldOffset, 0); }
  public static void addAskSpread(FlatBufferBuilder builder, int askSpreadOffset) { builder.addStruct(9, askSpreadOffset, 0); }
  public static void addAskGspread(FlatBufferBuilder builder, int askGspreadOffset) { builder.addStruct(10, askGspreadOffset, 0); }
  public static void addBidSize(FlatBufferBuilder builder, int bidSizeOffset) { builder.addStruct(11, bidSizeOffset, 0); }
  public static void addAskSize(FlatBufferBuilder builder, int askSizeOffset) { builder.addStruct(12, askSizeOffset, 0); }
  public static void addLastTradeSize(FlatBufferBuilder builder, int lastTradeSizeOffset) { builder.addStruct(13, lastTradeSizeOffset, 0); }
  public static void addLastTradePrice(FlatBufferBuilder builder, int lastTradePriceOffset) { builder.addStruct(14, lastTradePriceOffset, 0); }
  public static void addLastTradeTm(FlatBufferBuilder builder, int lastTradeTmOffset) { builder.addStruct(15, lastTradeTmOffset, 0); }
  public static int endMarketDataSnapshot(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishMarketDataSnapshotBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedMarketDataSnapshotBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MarketDataSnapshot get(int j) { return get(new MarketDataSnapshot(), j); }
    public MarketDataSnapshot get(MarketDataSnapshot obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

