// automatically generated by the FlatBuffers compiler, do not modify

package com.mattygiedt.flatbuffer.marketdata;

@SuppressWarnings("unused")
public final class Source {
  private Source() { }
  public static final int BPIPE = 0;
  public static final int TRACE = 1;
  public static final int CP_PLUS = 2;
  public static final int IHSM = 3;
  public static final int CEP = 4;
  public static final int ICEBP = 5;
  public static final int TMC = 6;
  public static final int TWD = 7;

  public static final String[] names = { "BPIPE", "TRACE", "CP_PLUS", "IHSM", "CEP", "ICEBP", "TMC", "TWD", };

  public static String name(int e) { return names[e]; }
}

